// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AppProvider: typeof import('./src/components/Application/src/AppProvider.vue')['default']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    EditorImage: typeof import('./src/components/Tinymce/components/EditorImage.vue')['default']
    IconFont: typeof import('./src/components/basic/icon-font/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tinymce: typeof import('./src/components/Tinymce/index.vue')['default']
    TitleI18n: typeof import('./src/components/basic/title-i18n/index.vue')['default']
  }
}

export {}
